[package]
name = "kvarn-auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13"
hmac = "0.12"
log = "0.4"
serde = "1"
serde_json = "1"
sha2 = "0.10"
